name = "1.21.1-NeoForge_21.1.216"
author = "strider_lee"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e424c2dff6ab6a02aef055deb9865287bbcaaf288aa8b1aac966c9bc1462d376"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
